export const defaultTheme = {
  colors: {
    'base-white': '#fff',
    'base-background': '#FAFAFA',
    'base-card': '#f3f2f2',
    'base-input': '#ededed',
    'base-hover': '#d7d5d5',
    'base-label': '#8d8686',
    'base-text': '#574f4d',
    'base-subtitle': '#403937',
    'base-title': '#272221',
    'base-button': '#e5e5e5',
    'base-error': '#f84747',
    'brand-purple-dark': '#4b2995',
    'brand-purple': '#8047f8',
    'brand-purple-light': '#ebe5f9',
    'brand-yellow-dark': '#c47f17',
    'brand-yellow': '#dbac2c',
    'brand-yellow-light': '#f1e9c9',
  },
  textSizes: {
    'text-title-xl': '3rem',
    'text-title-l': '2rem',
    'text-title-m': '1.5rem',
    'text-title-s': '1.2rem',
    'text-title-xs': '1.125rem',
    'text-regular-l': '1.25rem',
    'text-bold-l': '1.25rem',
    'text-regular-m': '1rem',
    'text-regular-s': '0.875rem',
    'text-bold-s': '0.75rem',
    'components-tag': '0.625rem',
    'components-button-g': '0.875rem',
    'components-buttons-s': '0.75rem',
  },
  fonts: {
    regular: "'Roboto'",
    title: "'Baloo 2'",
  },
}
